<?php $filters=$report_filters??['sources'=>[],'universities'=>[],'counselors'=>[]]; ?>
<div class="col-12" id="payment-report">
<div class="card card-outline card-primary"><div class="card-body py-3"><form id="payment-report-filter" class="row align-items-end">
<div class="col-sm-6 col-lg-2 mb-2"><label class="small text-muted">Student from</label><input class="form-control" type="date" name="start_date"></div><div class="col-sm-6 col-lg-2 mb-2"><label class="small text-muted">Student to</label><input class="form-control" type="date" name="end_date"></div>
<div class="col-sm-6 col-lg-2 mb-2"><label class="small text-muted">Source</label><select class="form-control select2" name="source_code" style="width:100%"><option value="">All sources</option><?php foreach($filters['sources'] as $v): ?><option value="<?=html_escape($v['source_code'])?>"><?=html_escape($v['source_name'])?></option><?php endforeach?></select></div>
<div class="col-sm-6 col-lg-2 mb-2"><label class="small text-muted">University</label><select class="form-control select2" name="university_id" style="width:100%"><option value="">All universities</option><?php foreach($filters['universities'] as $v): ?><option value="<?=$v['id']?>"><?=html_escape($v['university_name'])?></option><?php endforeach?></select></div>
<?php if(!empty($can_view_all)): ?><div class="col-sm-6 col-lg-2 mb-2"><label class="small text-muted">Counselor</label><select class="form-control select2" name="assigned_to" style="width:100%"><option value="">All counselors</option><?php foreach($filters['counselors'] as $v): ?><option value="<?=$v['id']?>"><?=html_escape($v['name'])?></option><?php endforeach?></select></div><?php endif?>
<div class="col-sm-6 <?=!empty($can_view_all)?'col-lg-2':'col-lg-4'?> mb-2 d-flex"><button class="btn btn-primary flex-fill mr-2">Apply</button><button type="button" id="reset-payment-report" class="btn btn-default"><i class="fas fa-undo"></i></button></div>
</form></div></div><div id="payment-report-alert" class="alert alert-danger d-none"></div>
<div class="row"><div class="col-md-6 col-xl-3"><div class="small-box bg-primary"><div class="inner"><h3 data-money="billed">—</h3><p>Total billed</p></div><div class="icon"><i class="fas fa-file-invoice"></i></div></div></div><div class="col-md-6 col-xl-3"><div class="small-box bg-success"><div class="inner"><h3 data-money="collected">—</h3><p>Collected · <span data-metric="collection_rate">—</span>%</p></div><div class="icon"><i class="fas fa-check-circle"></i></div></div></div><div class="col-md-6 col-xl-3"><div class="small-box bg-warning"><div class="inner"><h3 data-money="outstanding">—</h3><p>Outstanding balance</p></div><div class="icon"><i class="fas fa-wallet"></i></div></div></div><div class="col-md-6 col-xl-3"><div class="small-box bg-danger"><div class="inner"><h3 data-metric="overdue">—</h3><p>Overdue students</p></div><div class="icon"><i class="fas fa-calendar-times"></i></div></div></div></div>
<div class="row"><div class="col-sm-6 col-xl-3"><div class="card card-success card-outline"><div class="card-body"><small class="text-muted">Paid / Settled</small><h3 data-metric="paid">—</h3><span class="badge badge-success">Fully paid</span></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-warning card-outline"><div class="card-body"><small class="text-muted">Partial payment</small><h3 data-metric="partial">—</h3><span class="badge badge-warning">Balance remaining</span></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-danger card-outline"><div class="card-body"><small class="text-muted">Unpaid</small><h3 data-metric="unpaid">—</h3><span class="badge badge-danger">No payment yet</span></div></div></div><div class="col-sm-6 col-xl-3"><div class="card card-secondary card-outline"><div class="card-body"><small class="text-muted">Students without invoice</small><h3 data-metric="no_invoice">—</h3><span class="badge badge-secondary">Needs invoicing</span></div></div></div></div>
<div class="row"><div class="col-xl-8"><div class="card"><div class="card-header"><h3 class="card-title">Billing vs Collection</h3></div><div class="card-body"><div id="payment-trend" style="height:350px"></div></div></div></div><div class="col-xl-4"><div class="card"><div class="card-header"><h3 class="card-title">Payment Position</h3></div><div class="card-body"><div id="payment-status" style="height:350px"></div></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title font-weight-bold">Payment Follow-up Priority</h3><div class="card-tools"><span class="badge badge-danger">Overdue first</span></div></div><div class="card-body"><div class="table-responsive p-0"><table id="tb-payment-priority" class="table table-sm table-striped table-hover"><thead><tr id="th" data-thd="1"><th></th><th>Student</th><th>Invoice</th><th>Billed</th><th>Outstanding</th><th>Due date</th><th>State</th><th>Action</th><th></th></tr></thead><tbody></tbody></table></div></div></div>
</div>
